### ISSUE TITLE
Artifact mismatch from documentation

### ISSUE THREAD

**Issue by rrmcguinness** [hypercube1024/firefly#102]
The current readme has: 

```xml
<dependency>
    <groupId>com.fireflysource</groupId>
    <artifactId>firefly</artifactId>
    <version>5.0.2</version>
</dependency>
```

however, the artifact is not available in Maven Central, only 5.0.0-dev6 is the latest available.

**Comment by hypercube1024** [comment]
Sorry, the document error. The current artifact is :
`
<dependency>
        <groupId>com.fireflysource</groupId>
        <artifactId>firefly-net</artifactId>
        <version>5.0.2</version>
    </dependency>
`
