### ISSUE TITLE
How is this different from Vert.x?

### ISSUE THREAD

**Issue by jackzhp** [hypercube1024/firefly#37]
How is this different from Vert.x?

curious.

**Comment by hypercube1024** [comment]
Firefly provides the Kotlin DSL APIs, and the HTTP server or client executes business logic on coroutine. That means we can make the programs are shorter and far simpler to understand and enjoy the scalability and performance benefits of asynchronous codes.  For example:
```kotlin
fun main(args: Array<String>) {
    HttpServer {
        router {
            httpMethod = HttpMethod.GET
            path = "/"

            asyncHandler {
                end("hello world!")
            }
        }
    }.listen("localhost", 8080)
}
```

```kotlin
fun main(args: Array<String>): Unit = runBlocking {
    val msg = firefly.httpClient().get("http://localhost:8080").asyncSubmit().stringBody
    println(msg)
}
```

More details, please refer to the [Example (Kotlin version)](https://github.com/hypercube1024/firefly/tree/master/firefly-example/src/main/kotlin/com/firefly/example/kotlin)
